<?php 
$charactername = 'Zarksol';
$species = 'Dragon';
$sexuality = 'Pansexuel' ;
$relationship = 'Lié à une entité extra-planaire';
$divinity = 'Aucune';
$class = 'Voyageur Inter-Dimension';
$bodytype = '???/???/???';
$colors = 'Bleu/Bleu/Aucun';
$originalfeat = 'Rune anti-magie tatouer sur ses ailes';
$behaviour = 'Loyal-Calme-Polie-Enjoué/Froide-Féroce-Intrépide';
$background = "<p>Cadre de vie, de l'éclosion à l'âge d'apprendre.</p>
			<p>Zarksol a éclos dans la grande citadelle de cristal du domaine de la lumière, faussement appelé ''le royaume du bien'' par ses habitants. Bien que cela ne soit que de la propagande qui utilise l'image lumineuse et propre de ce territoire, la vie n'y est pas foncièrement mauvaise. Du moins, tant que l'on peut être utile d'une quelconque façon, ce royaume ressemblant plus à une méritocratie qu'autre chose.</p>
			<p>Presque tout y est construit d'une sorte de cristal qui a la propriété de pouvoir stocker de grande quantité de magie, l'absorbant lentement de l'environnement ou rapidement quand insufflé volontairement par quelqu'un.</p>
			<p>Celui qui stock cette énergie et affaiblis d'autant pendant un moment... Mais par simple contacte avec ces cristaux, il est également possible d'y puiser cette magie pour l'utiliser, et ce presque sans pertes, rendant ce stockage très utile sur le long terme. Cela permet également de lancer de sort bien plus puissant que si le lanceur ne disposait que de sa propre énergie du moment.<p>
			<p>Le royaume de lumière continue de bâtir son quotidiens sur ces cristaux, et ce malgré le fait de savoir depuis maintenant longtemps qu'ils épuisent lentement l'énergie de la planète en elle même. Les grands mages du royaume de lumière disent chercher des moyens de contrer cet effet, mais aucun progrès dans ce sens n'a encore jamais été annoncé.<p>
			<p>Le moyen radical de stopper ce lent siphonnage de la planète consiste a les ''corrompre''. Ils deviennent alors sombre et ne drainent plus d'énergie de façon passive. Il est toujours possible d'y stocker un peu d'énergie, mais il y a des pertes importantes dans le processus de transfert, et les cristaux ont la fâcheuse tendance a exploser quand soumis a trop d'énergie. Cette corruption s'étende en seulement quelques heures aux cristaux encore ''purs'' par simple contact, obligeant le royaume de lumière a toujours garder un œil attentif sur ses terres et leurs frontières.</p>
			<p>Le ''royaume des ténèbres'', comme l'appellent le habitants de la lumière, est bien plus grand, principalement composé de vastes étendues vides assombries par la \"corruption\". Ses habitants, toute personne de la lumière vous le dirait, sont malfaisant et cherchent a détruire le monde. En pratique, ce sont juste deux royaumes en guerre depuis tellement longtemps que la véritable cause n'est même plus certaine, bien que l'on suppose que ce soit surtout a cause de cristaux, et les deux royaumes se diabolisent mutuellement.</p>
			<p>La citadelle blanche, cœur du royaume de lumière, est fait de cristaux améliorés pendant des siècles et des siècles pour absorber toujours plus et plus vite, véritable réservoirs quasi inépuisable. Cette source énorme de puissance permet de faire de véritable merveilles même quand vous êtes vous même naturellement capable d'utiliser votre magie, pour peu que vous apreniez a la puiser dans le cristal.</p>
			<p>Les grand dômes d'énergie qui protègent la citadelle sont réputés indestructibles en grande partie grâce a cette énergie qui semble abondante et infinie. Les versions plus petits qui couvrent les villages isolés tiennent déjà en général suffisamment longtemps pour que de l'aide puisse venir, et les versions améliorées de la capitale n'ont encore jamais montré de signes de faiblesses.</p>
			<p>C'est dans ce cadre que Zarksol a grandis, l'un des très rare œufs de dragon à avoir éclos pendant les dernier siècles. Dés qu'il en a eu l'âge, il a dirigé ses études vers l'étude de la magie, étudiant les bases des écoles principales avant de se spécialiser dans les champs de force. Bien qu'il soit le fils de Kaëla, qui dirige le royaume de lumière, la culture de cette société l'a mis sur un pied d'égalité avec les autres, le mérite de chaque individus étant le seul véritable point reconnu pour juger d'une personne.</p>
			<p>De l'âge d'apprendre au grand changement.</p>
			<p>S'il était jugé au mieux médiocre dans presque toute les écoles de magie, sa perfection acharnée de l'école des champs d'énergie lui a permis d'être tranquille, lui laissant tout le temps nécessaire pour poursuivre ses recherches dans ce domaine jusqu'à concevoir ses propre variations des sorts existants. </p>
			<p>Au terme de ses études dans ce domaine, lors de la sélection de son école secondaire, il s'est dirigé vers l'invocation. Le choix lui semblait logique, puisque c'est l'une des écoles qu'il n'avait encore jamais pratiqué, et dans laquelle il n'avait donc encore jamais été jugé comme mauvais, les autres choix ayant ce même critère, tel que la nécromancie ou la magie incertaine de la téléportation, n'étant pas intéressants à ses yeux.</p>
			<p>S'il n'était pas aussi à l'aide avec l'invocation qu'avec les boucliers d'énergie, ail était quand même jugé décent dans cette école, et dés qu'il a eu des bases suffisamment solides, il a tenté de faire ses propres détournements de sorts, tentant de les modeler et de les modifier pour comprendre exactement comment cette magie fonctionne, plutôt que de juste l'utiliser sans chercher à savoir ce qui se passe.</p>
			<p>Sa soif d'expérimentation et de découverte l'a conduit vers les livres de magie de la citadelle de cristal, ou il a fouillé toujours plus profondément dans cet océan de savoir en quête de secrets et de compréhension. Jusqu'à tomber sur un livre décrivant des invocations jugées trop dangereuses pour être enseignées.
			Les méthodes d'invocation précises n'y étaient pas renseignées, de sorte qu'un mage avc peu de connaissances dans le domaine ne puisse s'y risquer... Mais de lectures en lectures, il est possible de déterminer comment invoquer certaines des créatures décrites. </p>
			<p>Zarksol a tenté de recréer autant de ces sorts que possible, sans les lancer, pour les comprendre et tacher de trouver s'il est possible de les améliorer pour les rendre moins dangereux. L'un d'eux décrivait une petite créature, d'à peine quelque dizaines de centimètres de haut, se nourrissant d'énergie pour survivre, utilisant le trop plein pour lancer des sorts simples de façon qui semble être instinctive. Un candidat parfait pour faire quelque tests, contrairement à certaines choses véritablement terrifiantes qui sont également décrites sur d'autres créatures.</p>
			<p>Les préparations se sont déroulées sans problème, l'énergie se modelant lentement à partir des cristaux sous les pattes du dragon bleu pour former ce qui doit servir de portail pour le passage de la créature. La sensation d'envoyer son énergie dans d'autres endroits à travers ces failles est toujours étrange, surtout quand, comme dans le cas présent, la cible semble... Loin, si cela peut avoir un sens. L'ouverture du passage est plus difficile, plus longue... Le passage semble moins stable, prêt à s'effondrer à tout moment, signe d'un sort sur le point de rater.</p>
			<p>Pourtant, la sphère d'énergie flottant dans l'air finis soudains par se stabiliser très rapidement, comme si une autre force œuvrait pour ouvrir le passage. La sensation familière de l'arrivée d'une invocation se fait sentir, le filet d'énergie envoyé dans l'inconnu revenant rapidement avec son nouvel occupant. Pourtant, plutôt qu'un soulagement et un sentiment d'accomplissement, c'est un froids glacial qui envahis Zarksol, avec le sentiment oppressant d'avoir commis une terrible erreur, sans savoir quoi. Le portail finis de s'ouvrir, laissant entrevoir une forme de quelque dizaines de centimètre se matérialiser rapidement, puis...</p>
			<p>Zarksol clique des yeux, regardant autour de lui quelque peu déboussolé. La sphère a disparue, et il n'est plus au même endroit. La nuit est presque tombée entièrement, alors qu'une minute avant le soleil était encore haut dans les cieux. Ses ailes semblent être en feu, brûlant de l'intérieur alors que son corps entier semble engourdis et fatigué. Pourtant, ce n'est rien de tout ça que le dragon bleu remarque, mais plutôt les long sillons de cristaux ternes partout autour de lui. Pas corrompus, juste... Vides. Vides de l'énergie sensée être quasi illimitée qui l'occupait il y a encore une minute.</p>
			<p>Partout, des bâtiments semblent être en ruines, ou sur le point de s'écrouler. Certains mages sont occupés à tenter de maintenir les choses en place dans les zones vidées, mais la majorité des personnes présentes restent la, sans bouger, les yeux grands ouverts o observer quelque chose. Zarksol se tourne pour regarder ce qui est derrière lui et qui attire tout ces regards, mais ou que se porte son propre regard, il ne vois que des yeux braqués sur lui, de plus en plus nombreux, remplis de questions, et de peur.</p>
			<p>L'exode.</p>
			<p>Bien que la citadelle soit encore secouée par l'attaque d'une créature inconnue, une sorte de tribunal exceptionnel a été réunis pour étudier et comprendre ce qui s'est passé, et agir pour que cela ne puisse plus se reproduire. Les théories du complot dénonçant un plan du royaume de l'ombre ont rapidement été écartés, et la vérité n'a pas tardée à être découverte, appuiée par le témoignage de l'accusé.</p>
			<p>Le cheminement ayant conduit à cette catastrphe a été retracé, et toute lesn otes sur le sujet ont été détruites, jugée comme trop dangereuse même pour être étudié. Après avoir étudié tout les détails de ce qui s'est passé avant l'invocation, les ailes de Zarksol ont été étudiée, mais rien n'a pu être découvert sur les étranges runes, le dragon bleu semblant résister malgré lui à toute les  tentatives d'étude, même avec les sorts les plus compliqués utilisés. Pourtant, ils ont insistés, tentant sort après sort pour percer le secret de ces runes, ou de les effacer. Sans succès.</p>
			<p>Le dragon bleu sent également que ce n'est pas lui qui résiste à cette magie, même involontairement, mais personne ne semble prêter attention à cette impression. Les tentatives continuent de se suivre, donnant une impression de danger de plus en plus pesante à Zarksol, son corps vibrant d'énergie, qu'il est pourtant incapable d'utiliser ou de canaliser.
			C'est à ce moment que la première explosion a eu lieu, toute cette énergie concentrée se libérant soudainement en une onde de choque, brisant les cristaux les plus fins et projetant les personnes proches à plusieurs mètres. Bien qu'au centre de ce déferlement d'énergie, Zarksol ne semble pas affecté, sentant un poids disparaitre de son corps avec soulagement. Jugé comme dangereux pour tout ceux qui l'entourent, il a été décidé de l'isoler le temps de décider quoi faire sur le long terme. La proposition d'un bannissement semble être de plus en plus populaire, avec certaines solution plus radicales.</p>
			<p>Kaëla regarda ainsi les débats se poursuivre, ne pouvant y participer de part son lien de parenté avec l'accusé malgré ses titres et ses avantages du à son rang. Mais ce débat à rallonge n'a jamais trouvé de fin, de plus en plus de monde se rassemblant pour y assister finissant par former une foule bruillante et colérique.</p>
			<p>Malgré les avertissements du tribunal exceptionnel, la foule finis par prendre d'assaut le bâtiment servant à isoler Zarksol du reste du monde. Il ne leur faut pas longtemps pour l'ouvrir, et pour que certains profitent de la confusion pour lancer toute sorte de sort plus ou moins dangereux. Prenant les airs pour s'échapper, le dragon bleu sème rapidement la majorité de la foule, incapable de voler, ne gardant que quelque poursuivant d'espèces diverses. </p>
			<p>Malgré la situation, une sensation étrange pousse Zarksol à se diriger vers le monument draconique non loin de la citadelle en elle même. Une grande surface plane formant un large cercle, entouré de statues représentant des dragons de races différentes qui semblent observer le centre du cercle, assis et l'air paisible. Il est dit que ces monuments servaient autrefois à traverser de grandes distances autrement insurmontables, mais voila bien des siècles que cela n'est pas arrivé... Et pourtant...</p>
			<p>Le début du voyage.<p>
			<p>A peine une patte posée sur le large cercle de pierre polie, une étrange énergie semble se dégager du monument, crépitant dans l'air inoffensivement. Les statues semblent presque vivantes, leurs yeux donnant l'impression d'observer Zarksol, de le juger. Le temps semble ralentis, les quelque poursuivant du dragon bleu s'arrêtant à bonne distance pour observer, pendant que les autres fuient de peur d'un nouveau désastre.</p>
			<p>Mais pendant un moment, rien ne semble se passer... Du moins, de l'exterieur. A l'interrieur du cercle, Zarksol peut sentir cette étrange énergie le parcourir, puissante et indomptable, frappant parfois ses ailes comme pour le provoquer, sans qu'il ne semble rien se passer de particulier. </p>
			<p>Le jeune dragon observe ce qui l'entours, terrifié et ne comprenant pas ce qui arrive, alors que la réalité du monde qui l'entours semble s'estomper, les bâtiments s'effacent doucement derrière la surface de la sphère d'énergie ondulant lentement autour du monument. Des cris attirent son attention, son regard se tournant vers une silhouette blanche se dessinant dans le ciel, si proche, et pourtant si loin... Jusqu'à disparaitre complètement.</p>
			<p>Le royaume de lumière laisse place à l'obscurité totale. l'espace de quelque secondes, il deviens impossible de discerner quoi que ce soit. Par réflexe, il tente de cracher son feu liquide pour avoir de la lumière, mais les ténèbres persistent sans montrer la moindre lueur pendant plusieurs longues secondes de plus... Avant d'être balayés par une lumière éblouissante.
			Autour de lui, plus de cristaux, plus de citadelle, plus de foule ou de cris... Juste le bruissement du vent dans ces étranges constructions marron au toit vert, avec parfois de petit motifs colorés. Le sol semble également couvert de ce même genre de construction verte, se balançant au vent, chaque brin indépendant du suivant. Dans le ciel, d'étranges petite créatures collent en sifflant une musique répétitive mais plaisante. Ou que soit cet endroit, ce n'est ni le royaume de lumière, ni celui des ténèbres... Peut être le continent d'Alielna, qui s'est isolé face à la guerre et aux conflits permanant ? Ou d'autres terres plus lointaines ?</p>
			<p>Il ne fallu pas longtemps pour se rendre compte que ce nouveau monde est totalement différent, avec très peu de points communs avec la d'ou Zarksol viens, si ce n'est le monument, qui semble pourtant plus vieux, moins bien entretenu, avec l'une des statues en ruine... L'air est cependant bien plus frais ici, et tout semble paisible. Peut être une sorte de paradis ? Un monde après la mort ?</p>
			<p>Si tel est le cas, alors il y a plusieurs paradis, dont la porte menant entre ces mondes mène également à des enfers. Certains mondes sont même peuplés de créatures fondant leur société sur la \"technologie\", et non sur la magie. D'autres ont les deux. Certains sont en paix, d'autres en guerre permanente... Tellement de monde, tellement de découvertes et d'étrangetés.
			Au fil des années, Zarksol a finis par oublier les circonstances exactes de son départ, les points au départ douloureux laissant place à un désir de comprendre, de vaincre cette chose qui l'a marqué et qui l'a indirectement chassé de chez lui, et de rentrer dans son monde. Parfois, dans ses rêves, il revois cette silhouette blanche approchant à tire d'aile de lui, troublé par la magie qui l'entoure, avec une voix déformée lui criant quelque chose qui semble être important, ou peut être désespéré...</p>
			<p>Monde après monde, ne restant jamais très longtemps, il en apprends un peu plus sur l'univers. Parfois, il s'attarde un peu dans un monde qui semble avoir des réponses à ses questions les plus importantes, avant de passer au suivant... Et un jours, passant de nouveau dans cette obscurité totale, il se retrouve dans un lieu qui semble être sous terre, le monument gisant en ruine presque totalement. Un monde ou la magie semble omniprésente, et ou, peut être, se trouvent des réponses à ses questions... Voir des clefs à ses problèmes. Lentement, il s'avance dans les couloirs sombres de ces catacombes, sous un château en ruine, dans un monde amplis d'aventures.</p>";
$weapon = 'Griffe/Croc/Queue';
$armor = 'Écailles';
$picture = 'zarksol.jpg';
?>